name: carebridge
description: A dual-service ecosystem connecting Pet Owners with Verified Caretakers and Adoption Hubs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  glassmorphism_ui: ^0.3.0
  http: ^1.1.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  image_picker: ^1.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  font_awesome_flutter: ^10.6.0
  animations: ^2.0.11
  firebase_core: ^3.10.1
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.4
  firebase_storage: ^12.4.10
  razorpay_flutter: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoicon.png"
  min_sdk_android: 21
